project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - r_illust.qmd
    - jdcov.qmd

website:
  title: "beyond-correlation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: r_illust.qmd
        text: R
      - href: jdcov.qmd
        text: Python

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



