---
title: "Beyond pairwise correlation: capturing nonlinear and higher-order dependence with distance statistics"
authors:
  - name: Benjamin Avanzi
    affiliation: Centre for Actuarial Studies, Department of Economics, University of Melbourne, Australia
  - name: Guillaume Boglioni Beaulieu
    affiliation: School of Risk and Actuarial Studies, University of New South Wales, Sydney, NSW 2052, Australia
  - name: Pierre Lafaye de Micheaux
    affiliation: School of Mathematics and Statistics, University of New South Wales, Sydney, NSW 2052, Australia
  - name: Ho Ming Lee
    affiliation: 
      - Centre for Actuarial Studies, Department of Economics, University of Melbourne, Australia
      - Faculty of Economics and Business, KU Leuven, Belgium
    corresponding: true
  - name: Bernard Wong
    affiliation: School of Risk and Actuarial Studies, University of New South Wales, Sydney, NSW 2052, Australia
  - name: Rui Zhou
    affiliation: Centre for Actuarial Studies, Department of Economics, University of Melbourne, Australia
bibliography: references.bib
output:
  html_document:
    toc: true
    number_sections: true
    df_print: paged

editor_options:
  markdown:
    wrap: 72
---
This is the home page for the code replicating the modelling and visualisation results for the paper Beyond pairwise correlation: capturing nonlinear and higher-order dependence with distance statistics, submitted to the 2026 All Actuaries Summit in Melbourne, Australia. In the paper, we introduce several distance-based dependence statistics, including the Hellinger correlation [@geenens2022hellinger], distance covariance [@szekely2007measuring], joint distance covariance [@chakraborty2019distance], and the (multivariate) auto-distance correlation function for time series applications [@fokianos2018testing, @zhou2012measuring]. The illustrations for the Hellinger correlation, distance covariance, and the (multivariate) auto-distance correlation function are implemented in `R` and can be viewed by clicking [here](r_illust.qmd) or the `R` page at the top. The illustration for joint distance covariance is implemented in `Python` and can be assessed [here](jdcov.qmd) or by clicking the `Python` page at the top.
